version: "3.8"

services:
  db:
    image: mariadb:10
    command: mysqld --character-set-server=utf8mb4 --collation-server=utf8mb4_general_ci
    ports:
      - "${DB_PORT:-3306}:3306"
    environment:
      - MARIADB_DATABASE=app_development
      - MARIADB_ROOT_PASSWORD=password
    volumes:
      - db-data:/var/lib/mysql

  app:
    build: .
    volumes:
      - .:/app
      - bundle:/usr/local/bundle
      - node_modules:/app/node_modules
      - /app/vendor
      - /app/tmp
      - /app/log
    ports:
      - "${APP_PORT:-3003}:3000"
    links:
      - db
    environment:
      - DATABASE_USERNAME=root
      - DATABASE_PASSWORD=password
      - DATABASE_NAME=back_development
      - DATABASE_HOST=mysql
    tty: true

volumes:
  db-data:
    driver: local
  bundle:
    driver: local
  node_modules:
    driver: local  
